#!//Library/Frameworks/Python.framework/Versions/3.8/bin/python3

import sys
sys.path.append("scripts")
from deploy import deploy

import os
import shlex
import subprocess

if len(sys.argv) < 3:
    print("Usage: " + sys.argv[0] + " disease_id target_path")
    sys.exit(1)

src_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(src_path)

DISEASE_ID = sys.argv[1]
TARGET_PATH = sys.argv[2]

if os.path.exists(TARGET_PATH):
    print("Target '" + TARGET_PATH + "' already exists. "
          "Please make a back-up and remove it.")
    sys.exit(1)
os.mkdir(TARGET_PATH)

if __name__ == '__main__':
    deploy(DISEASE_ID, TARGET_PATH)
